### PR TITLE
Updating to UFR, including improvements from Anna's repro, STAT table correction

### PR DESCRIPTION
**Pull request by aaronbell**
The NEGA axis has been disabled in this PR for GF purposes, but swapping the "signika.designspace" with "signika_2axis.designspace" will re-enable the axis.

### CODE REVIEW

**Comment by kontur** [comment]
@aaronbell Could this PR update the README as regards to the build instructions?

**Comment by kontur** [comment]
ping @aaronbell see my comment above :)

**Comment by aaronbell** [comment]
@kontur Hey! Sorry. I've updated the README with the build instructures per the UFR approach. It is much shorter! :)

See what you think.

**Comment by kontur** [comment]
@aaronbell thanks, that looks neat! Easy enough to follow, should we get to work on implementing the `GRAD` axis for the VF. Personally I'm not familiar with the make file syntax, but I suppose if we need to add additional steps etc. it's just a matter of adding different script calls as new lines there. 👍

**Comment by aaronbell** [comment]
👍 I think it would be relatively simple to add in the `GRAD` in by adding a new designspace document and then building from that. All the instances are there.

**Pull request merged**
